baseurl = "https://www.serrestech.gr/"
title = "SerresTech - The Technology community of Serres, Greece"
theme = "serrestech"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics
googleAnalytics = "UA-6649652-62"
publishDir = "docs"

# Define the number of posts per page
paginate = 10

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Meetups"
    url  = "/categories/meetups/"
    weight = 3
[[menu.main]]
    name = "News"
    url  = "/blog/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "Meetup"
    url = "https://www.meetup.com/Serrai-Software-Development-Meetup"
    pre = "<i class='fab fa-2x fa-meetup'></i>"
[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/serrestech"
    pre = "<i class='fab fa-2x fa-github'></i>"
[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/SerresTech"
    pre = "<i class='fab fa-2x fa-facebook'></i>"
[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/serrestech"
    pre = "<i class='fab fa-2x fa-twitter'></i>"
[[menu.topbar]]
    weight = 5
    name = "RSS"
    url = "/index.xml"
    pre = "<i class='fa fa-2x fa-rss'></i>"
[[menu.topbar]]
    weight = 6
    name = "Email"
    url = "mailto:info@serrestech.gr"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "Serrestech"
    defaultKeywords = []
    defaultDescription = ""
    baseUrl = "https://www.serrestech.gr"
    twitterUsername = "serrestech"
    hashtags = "serrestech, meetup, serres"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@serrestech.gr"

    about_us = ""
    copyright = "Copyright &copy; 2019, SerresTech. All rights reserved. <br><b>SerresTech - The technology community of Serres, Greece.</b>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

[Permalinks]
    blog = "/blog/:year/:month/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = '<h5 class="text-light-gray hidden-sm hidden-xs">We are the technology community of Serres, Greece</h5>'

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = 0

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = 0
    # All features are defined at '/data/features'.

[params.teasers]
    enable = true

[params.testimonials]
    enable = true
    # All testimonials are defined at '/data/testimonials'.
    title = "Our Members"
    subtitle = "We are open to any people. Have a look what our members say about SerresTech."

[params.see_more]
    enable = 0
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined at '/data/clients'.
    title = "Our Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = 1
    title = "Latest news"
    subtitle = ""
