backend:
  name: git-gateway
  identity_url: "https://www.serrestech.gr/.netlify/identity"
  gateway_url: "https://www.serrestech.gr/.netlify/git/github"
  branch: master
media_folder: "static/img/banners"
public_folder: "/img/banners"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
